version: "3"

# Ref https://docs.docker.com/compose/compose-file/

services:
  nginx:
    image: 'laptrinhcomvn/ltpro_nginx:latest'
    container_name: nginx
    environment:
      - ENABLE_IPV6=true
      - TZ=Asia/Ho_Chi_Minh
    working_dir: /usr/www/src
    networks:
      - backend
      - frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./src:/usr/www/src
    

  phpfpm:
    image: 'laptrinhcomvn/ltpro_phpfpm:latest'
    container_name: phpfpm
    environment:
      - ENABLE_IPV6=true
      - TZ=Asia/Ho_Chi_Minh
      - PHP.upload_max_filesize=1000M
      - PHP.post_max_size=1000M
      - PHP.max_execution_time=1200
    working_dir: /usr/www/src
    networks:
      - backend
      - frontend
    restart: always
    expose:
      - "9000"
    volumes:
      - './src:/usr/www/src'
    
  
  mysql:
    image: 'mysql:8.0.20'
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: mysql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_ROOT_PASSWORD=TVUhnqbgL6kTZ4VT
    volumes:
      - './mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './mysql/data:/var/lib/mysql'
    networks:
      - backend
    restart: always
    ports:
      - '3306:3306'

networks:
  backend: null
  frontend: null